### ISSUE TITLE
vetKey's private key is not stored locally?

### ISSUE THREAD

**Issue by hokosugi** [NeutronStarDAO/ICCookBook-English#3]
> Even if someone hacks device A or B, the private key won't leak directly, 'cause the user ID private key ain't stored locally. 

Above is the second half of `vetKey.md`. Isn't the public key pair generated based on the generated community ID, and the private key sent to each user with the transport key? If the communityID is not updated, wouldn't this private key be local to the user? If you update this ID every time you communicate, then the private key corresponding to the updated ID would not be local. However, would it be practical to update it each time, considering the cost and effort involved?

Here is a video that gives the rationale for thinking this way.
https://youtu.be/baM6jHnmMq8?t=1318

The encrypted_key is decrypted locally in ⑥.
I was a little concerned about this, so I asked the question. I'm not sure I understand vetKey, so I could be wrong.

**Comment by NashAiomos** [comment]
Yes, you are right that the statement has issues. Thank you for the feedback. 

> Even if someone hacks device A or B, the private key won't leak directly, 'cause the user ID private key ain't stored locally.

What it meant to say is that users can derive the decryption key (private key) corresponding to an ID (public key) through key derivation. The decryption key can be deleted after use, instead of being persistently stored locally. This is more secure than the traditional approach of public key encryption, where users have to store private keys locally at all times.

I will make changes.

<hr>

Indeed, changing the ID and re-deriving keys every time would incur additional computation and communication costs. However, IDs can be reused appropriately depending on the application scenario to strike a balance between security and efficiency.
